version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    # or image
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=mariadb://user:password@db/mydatabase
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: arm64v8/mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:

